kind: Service
apiVersion: v1
metadata:
  name: service-core-code-school
spec:
  type: LoadBalancer
  selector:
    app: core-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
